project_id = "suhnrxcjukzsyddqqbxj"

[functions.trip-planner]
verify_jwt = false

[functions.generate-itinerary]
verify_jwt = false

[functions.edit-trip]
verify_jwt = false

[functions.calculate-logistics]
verify_jwt = false
